# https://github.com/apps/settings
repository:
  name: cloud-dev-env
  description: devcontainerでクラウド(Azure, AWS)上で動作する基盤アプリ(python)の開発環境
  homepage: https://github.com/apps/settings
  topics: azure, aws, python, poetry
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false

branches:
  - name: main
    protection:
      # required_pull_request_reviews:
      #   required_approving_review_count: 1
      #   dismiss_stale_reviews: true
      #   require_code_owner_reviews: false
      #   dismissal_restrictions:
      #     users: []
      #     teams: []
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []
