python_version = "3.12"
show_error_context = true    # エラー時のメッセージを詳細表示
show_column_numbers = true   # エラー発生箇所の行数/列数を表示
disallow_untyped_defs = true # 関数定義の引数/戻り値に型アノテーション必須
no_implicit_optional = true  # デフォルト引数に None を取る場合型アノテーションに Optional 必須
check_untyped_defs = true    # 型注釈がない関数やメソッドに対して型チェックを行う
warn_redundant_casts = true  # 冗長なキャストに警告

[overrides]
module = ['requests/*', 'psutil']
ignore_missing_imports = true
