name: Docker Build and Push to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  docker_build_push_ghcrio:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: "ghcr.ioへのログイン(gha)"
        if: github.actor != 'nektos/act'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "ghcr.ioへのログイン(act)"
        if: github.actor == 'nektos/act'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "メタデータを作成する(gha)"
        if: github.actor != 'nektos/act'
        id: meta # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: "メタデータを作成する(act)"
        if: github.actor == 'nektos/act'
        id: meta # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ vars.GITHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}/sample
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: test
        run: echo "ghcr.io/${{ vars.GITHUB_USERNAME }}/${{ vars.REPOSITORY_NAME }}"

      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
