name: Docker Build and Push to ghcr.io

on:
  push:
    branches:
      - main

jobs:
  docker_build_push_ghcrio:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: set variable in Github Action
        if: ${{ github.actor != 'nektos/act' }}
        run: |
          echo "GITHUB_USERNAME=${{ github.actor }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: set variable in act
        if: ${{ github.actor == 'nektos/act' }}
        run: |
          echo "GITHUB_USERNAME=${{ vars.GITHUB_USERNAME }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${{ vars.REPOSITORY_NAME }}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: "ghcr.ioへのログイン"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USERNAME }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: "メタデータを作成する"
        id: meta_act # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.GITHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}/sample
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: "コンテナイメージのビルドとghcr.ioへのプッシュ"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          push: true
          tags: ${{ steps.meta_act.outputs.tags }}
          labels: ${{ steps.meta_act.outputs.labels }}
